import React from 'react'

export default function SidebarContents() {
  return (
    <div>SidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContentsSidebarContents</div>
  )
}
